# -*- coding: utf-8 -*-
"""Copy of scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgsKfPzb9Dg03eyVwU0n93cx7Ki0giWS
"""

import pandas as pd

df=pd.read_csv('/content/covid_toy - covid_toy.csv')

df.head(2)

df.isnull().sum()

#descreate(categoical) --> we cannot divide further ex. result(pass,fail),
#marital status,number of empolyees

# continues(numerical)-->

df['fever']=df['fever'].fillna(df['fever'].mean())

df['has_covid'].value_counts()

df['gender']=df['gender'].map[('female':0,'male':1)]

df['cough']=df['cough'].map[('mild':0,'strong':1)]

df['city']=df['city'].map[('kolkate':0,'dehli':1)]

df['has_covid']=df['has_could'].map[('No':0,'yes';1)]

df = df.dropna()

df.head(3)

df.describe()

#x=1,2,3,4
#mean = (1+2+3+4) =10/4=2.5

df['fever']=df['fever'].astype(int)

a=df[['gender','fever']][3:7]=50

df.head(3)

df['fever'][1]=500

df.rename(columns={'fever':'update_fever'})

