# -*- coding: utf-8 -*-
"""Copy of scratchpad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KgsKfPzb9Dg03eyVwU0n93cx7Ki0giWS
"""

import pandas as pd

df=pd.read_csv('/content/covid_toy - covid_toy.csv')

df.head(2)

df.isnull().sum()

#descreate(categoical) --> we cannot divide further ex. result(pass,fail),
#marital status,number of empolyees

# continues(numerical)-->

df['fever']=df['fever'].fillna(df['fever'].mean())

df['has_covid'].value_counts()

df['gender']=df['gender'].map[('female':0,'male':1)]

df['cough']=df['cough'].map[('mild':0,'strong':1)]

df['city']=df['city'].map[('kolkate':0,'dehli':1)]

df['has_covid']=df['has_could'].map[('No':0,'yes';1)]

df = df.dropna()

df.head(3)

df.describe()

#x=1,2,3,4
#mean = (1+2+3+4) =10/4=2.5

df['fever']=df['fever'].astype(int)

a=df[['gender','fever']][3:7]=50

df.head(3)

df['fever'][1]=500

df.rename(columns={'fever':'update_fever'})

parts of EDA
 1. univeriate analysis => analysis on a single independent columns
 2. Biveriate analysis => analysis on two columns
 3. multivariate analysis => analysis on more two columns

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/titanic - titanic.csv')

df

df.columns

df['Survived'].value_counts

df['Survived'].value_counts().plot(kind='bar')

sns.countplot(x=df['Ticket'])

df['Survived'].value_counts().plot(kind='pie',autopct='%.2f')

plt.hist

# Boxpilot
# for find the outliers

# 1. lower fence
# 2. 25% data
# 3. IQR(Inter quartlie range)(75%-25%)
# 4. 75% data
# 5. upper fence

#x=1,2,3,4,5
# mean= (1+2+3+4+5)/5 =15/5 =3
# x = 1,2,3,4,5,100
# mean=15+100/6

df

df['PassengerId'].value_counts().plot(kind='pie',autopct='%.2f')



df

tips=sns.load_dataset('tips')

tips

sns.scatterplot(x=tips['total_bill'], #df['total_bill']
                 y=tips['tip'])

# scatterplot(numerical columns  - numerical columns)

sns.scatterplot(x='total_bill',y="tip",data=tips,hue=tips['sex'])

sns.scatterplot(x='total_bill',y="tip",data=tips,hue=tips['sex'],style=tips['smoker'])

#heatmap(categorical- categorical)
p=pd.crosstab(tips['day'],tips['time'])

sns.heatmap(p)



"""#Employee attrition analyais

employee ATTRItion analysis is atype of behavioural analysis where we study the behaviur and characteristics of the employee  who left the organization and compare their characteristic with the current employee to find the employees who may leave the orgenization soon
"""

#a high rate of attrition of employees can be expensive for any company in terms of recruitment and training costs,loss of productivity and morale reduction of employees. by identiflying
#the causes of attrition ,a company can take measures to reduce the attrition of employees and maintain pracious employees

import numpy as np
import pandas as pd

df=pd.read_csv('/content/Attrition - Attrition.csv')

import plotly.graph_objects as go
import plotly.io as plo
plo.templates.default= "plotly_white"

df

print(df.isnull().sum())

# check percentage of attrition by department

# calculate the attrition by department

hd=df[df['Attrition']=='Yes']

hd.head(2)

hdby_department=hd.groupby(['Department']).size().reset_index(name="count")

hd.groupby(['Department']).size()

#create a donut chart
fig= go.Figure(data=[go.Pie(labels=hdby_department['Department'],
                               values=hdby_department['count'],
                            hole=0.4,
                            marker=dict(colors=['red','green']),
                            textposition='inside')])

# update the layout
fig.update_layout(title_text='Attrition by Department')

# show the chart
fig.show()

fig

#we can see that the empolyee with life science as an education field have a high attrition rate. now let's
#have a look at the percentage of attrition by number of years at the company

group=hd.groupby(['YearsSinceLastPromotion']).size().reset_index(name='Count')

group

#now the relation of montly income vs employee increage

import plotly.express as px

fig=px.scatter(df,x="Age",y="MonthlyIncome",color="Attrition",
              trendline="ols")
fig.update_layout(title="Age vs Monthly Income by Attrition")
fig.show()