# -*- coding: utf-8 -*-
"""workquestion27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ldmq8_1CIAHeWpuRjaCKE8H3A8Cw2HVQ
"""

import pandas as pd

df=pd.read_csv('/content/Amazon Sale Report - Amazon Sale Report.csv')

df

df[df['B2B']==False]
print(df)



df = pd.read_csv('/content/Amazon Sale Report - Amazon Sale Report.csv', low_memory=False)

df = pd.read_csv('/content/Amazon Sale Report - Amazon Sale Report.csv')
df.head(5)

df.tail()

df['Category'].unique()

df['Category'].nunique()

df['Fulfilment'].unique()

df['Status'].nunique()

df

df['B2B']=df['B2B'].astype=str

df

df.shape

df.columns

df.dtypes

df['Date'] == pd.to_datetime(df['Date'], format='%Y-%m-%d')

df

df['Date'] = pd.to_datetime(df['Date'], format='mixed')

df

df.isnull().sum()

df.isnull().sum().sum()

hd=df['Amount'].mean()

df['Amount'].isna().sum()

df['Amount'].fillna(hd)

df['Qty'].fillna(0)

hd=df.dropna(subset=['Date'])

df['Sales']

hd

df[df['Status']=='Shipped']

df[df['Qty']>5]

df['Sales Channel']

df[df['Amount']>1000]

df

df['B2B']

df.sort_values(by='Amount',ascending=True)

df.sort_values(by='Date',ascending=False)

df.sort_values(by='Amount',ascending=True)

df.sort_values(by='Amount',ascending=False)

df['Total_Value']=df['Amount']*df['Qty']

df

df['High_Value_Sale']=df['Amount']>2000

df

df['Order_Type']=df['B2B']==True

df

df.groupby('Category')['Amount'].sum()

df.groupby('Fulfilment')['Amount'].sum()

df.groupby('Style')['Qty'].sum()

df.groupby("Status")['Order ID'].count()

df.groupby('B2B')['Amount'].sum()

df['Date'].dt.year

df['Date'].dt.month

df['month']=df['Date'].dt.month
df.groupby('month')['Amount'].sum()

df['month']=df['Date'].dt.month
df.groupby('month')['Amount'].sum()